### ISSUE TITLE
Discover: add a small "x" in the right corner of search window after search has been started to stop search mode and clear the search field

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#104]
Thats useful in cases when one starts to search e.g. for "frog", then clicks on 
Plasma Addons and then Aurorae Window Decorations and just wants to clean/break from the search mode.

the clear search-field aspect is easy and useful, the "exit search mode" part could need some extra finetune from VDG.

**Comment by aleixpol** [comment]
https://commits.kde.org/discover/dedc571166db34ab0f8e7faf59162c069e65310d
