### ISSUE TITLE
Discover: Categories are double, one time spelled with "and" and one time with "&"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#110]
example:
![screenshot_20171225_134616](https://user-images.githubusercontent.com/840070/34343148-2b17265e-e97a-11e7-8ba3-3bf9629950d4.png)

this is tested on latest Rolling version, Plasma 5.11.4

**Comment by aleixpol** [comment]
https://commits.kde.org/discover/db212c8efdf23e4b4475e0f320eab0522ee81dae
