### ISSUE TITLE
folderview: reduce horizontal space between icons

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#112]
compared to 5.11.4 the icon grid in neon dev unstable looks like it has expanded horizontal space.

Imo the 5.11.4 space looks great, maybe it simply hasn't been set in git unstable 5.12 aka regressed?

Otherwise also drag and dropping worked fine placing it underneath another icon, which on neon-unstable pinebook has regressed too.

Tldr; suggesting to restore the grid size / spacing and dnd of 5.11.4, just fixing that the first icon gets selected (see other ticket).

Here is a screenshot of current 5.11.4 as tested on latest Rolling img:
![screenshot_20171225_150535](https://user-images.githubusercontent.com/840070/34343507-1489c82c-e986-11e7-99f9-ab4692bdf8e3.png)

**Comment by eikehein** [comment]
Unless I am forgetting something, I don't think we did any code changes since 5.11 that affect horizontal grid spacing.

That means I need to do some detective work first and find out what is going on, e.g. by comparing images. What distro are you comparing 5.11.4 and git unstable in, Netrunner vs. Neon? Is the theme the same? Which theme? Image links would be ideal and I'll investigate!

**Comment by star-buck** [comment]
Netrunner Rolling compared to Neon Pinebook Remix.
I recall we talked about slightly reducing the Grid space at Paderborn, so I am not sue if that affected 5.11.90 on Neon or if its just the Breeze theme that makes it appear so.
I just noticed some things like the grid drod behaviour changed and it looked as if the grid size is different, but I could be wrong.
If nothing has changed, I guess just ignore it for now :)

**Comment by eikehein** [comment]
In Paderborn we talked about reducing the vertical grid space, which went into master last week to be released with 5.12 soon :). It's a small change though.

**Comment by star-buck** [comment]
Then I need to re-check, it looks like it either stayed the same or maybe
its due to resolution issues judging from pinebook neon default with its
reduced resolution vs. plasma 5.11.5 on the desktop at standard resolultion
1920x1080, but i need to recheck carefully
