### ISSUE TITLE
samba-mounter: latest update requires adding version parameter when mounting

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#116]
Latest system update I got this error message:
![screenshot_20180121_171214](https://user-images.githubusercontent.com/840070/35196233-961bcc2e-fecf-11e7-921b-211179f34e52.png)

According to here it needs some version number parameter:
https://serverfault.com/questions/414074/mount-cifs-host-is-down

e.g.:
sudo mount -t cifs -o vers=1.0

I am not sure if to automatize correct version number, or if we simply add lowest one.
@aleixpol:
Needs a quick fix of the code, plus then rebuilding package and testing.

**Comment by aleixpol** [comment]
I looked into this issue in the past, I didn't act on it because the spec specifically states that older versions of the protocol hinder security.
We could try to remount with an older protocol if the default behaviour doesn't work.

**Comment by star-buck** [comment]
Of course its now 100% secure as it doesnt work anymore.
Lets try and fix this so it works again in those cases it doesnt anymore right now.

**Comment by aleixpol** [comment]
https://commits.kde.org/samba-mounter/2f797e2ccb5df52810d84c50e4b49ed8f08a9570

**Comment by star-buck** [comment]
works again now, thanks @aleixpol !

Could you also make it work again that hitting the "ok" button does always behave like if triggered the save button? or at least not add a folder that then isnt connected to the samba share, but only a placeholder? Open for suggestions.
