### ISSUE TITLE
[breeze gtk icons]: missing icons, e.g. on buttons or window-titlebar for gnome-chess

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#12]
there seem to be some missing icons e.g. in gnome-chess titlebar:
![gtk3-missing icons](https://cloud.githubusercontent.com/assets/840070/17510623/0892683c-5e20-11e6-83d1-36373bce94ba.png)
Does anyone know if its just a missing package?

**Comment by jriddell** [comment]
Breeze artist Andreas K says he'll make breeze icons cover all icons in adawita which would solve this

**Comment by star-buck** [comment]
imo thats only a catchup and could break again temporary every now and then.
Doesnt this also make breeze icon set huge and a mixed bag with non-breezish adwaita?
Why not use the fallback method correctly, which is possible for gtk2 and gtk3 as well?

**Comment by star-buck** [comment]
ok/cancel button also affected:
![screenshot_20161005_111846](https://cloud.githubusercontent.com/assets/840070/19147225/72aeb210-8bb7-11e6-9c64-3b6654520f16.png)
