### ISSUE TITLE
Discover: size in detail page is "0 B" again, for apps and also for OCS-stuff

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#123]
https://www.dropbox.com/s/w198m4e812igwlr/discover-5.12.1.mkv?dl=0

**Comment by NuLogicSystems** [comment]
Link is wrong, It's taking me to my dropbox not yours..

**Comment by aleixpol** [comment]
The link says `The folder ‘/plasma-issues/plasma-5.12’ doesn’t exist.`.

**Comment by star-buck** [comment]
I changed the link, please load the comment on github again.

**Comment by aleixpol** [comment]
Downloaded netrunner rolling and will be testing on it on a virtualbox.
Regarding the video, I'm also concerned about how the install buttons are disabled. This shouldn't happen... :thinking:

**Comment by aleixpol** [comment]
There's this bug report about PackageKit on Manjaro: https://github.com/hughsie/PackageKit/issues/237 
Could be relevant.

**Comment by NuLogicSystems** [comment]
Yes, that is exactly the problem.
Comment out the SyncFirst line from the pacman.conf file and Discover (packagekit) works as it should.
It's not a bug, the problem is that Manjaro is still using this depreciated feature.
https://github.com/netrunner-rolling/2018.01/issues/55
