### ISSUE TITLE
Discover: Store items: sort by (release) date should be showing the latest first, OR add "sort by update date" and sort it by latest update date first

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#136]
example "Comics" sort by date shows the oldest comics first, which probably is not what the user wants/expects if sort by date.
Assumed is the user would like to see whats the latest/newest stuff first, so when frequently checked, it is easy visible when there is something new without always scrolling to the "end" of each list to see latest first last.

**Comment by aleixpol** [comment]
Should be fixed as of https://commits.kde.org/discover/b6a3d2bbf1a75bac6e48f5ef5e8ace8f770d535c
