### ISSUE TITLE
dashmenu: when some category entries are hidden on left side due to not enough height, either show scrollbar when mouse hovering over that area or always show scrollbar

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#144]

**Comment by eikehein** [comment]
Hmm, category entries on left side? The Dashboard has the categories on the right (with a scrollbar) ...

**Comment by star-buck** [comment]
Yes, right side, sry. Does the scrollbar become visible when overflowed? I
mean without the user actually scrolling up or down, but before that as an
indicator either all time visible when overflown or when hovering over that
area.

**Comment by llelectronics** [comment]
I see a scrollbar here: https://i.imgur.com/XclWpfM.jpg

**Comment by eikehein** [comment]
Yep:

![screenshot_20181203_200727](https://user-images.githubusercontent.com/2744902/49370441-756ade00-f737-11e8-81b5-52e2a4b812be.png)
Theme issue?

**Comment by star-buck** [comment]
not visible here (not a theme issue) while there is clearly one for the apps:
![screenshot_20181203_080542](https://user-images.githubusercontent.com/840070/49375523-8a615600-f6d2-11e8-9b20-c6e803b0f62d.png)

So for lower resolutions like over VNC i guess it is just there but too crammed?

**Comment by star-buck** [comment]
okay, it is there but "over the edge" ;) lets just leave it as is for now, its not superimportant.
![screenshot_20181203_081000](https://user-images.githubusercontent.com/840070/49375640-ed52ed00-f6d2-11e8-983a-c50fd4e428d7.png)

**Comment by llelectronics** [comment]
Looks like it might be really a resolution issue as it looks to my the dash is not fitting in the screen at all. So the scrollbar might be visible outside the screen

**Comment by eikehein** [comment]
Definitely means it's a bug though, will put on my todo
