### ISSUE TITLE
KDE Applications: About: have consistent info, like Timestamp and actual version number

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#150]
I am not sure if Marble is supposed to be part of the KDE Apps Bundle, but assuming so from the branching et. al.:
https://cgit.kde.org/marble.git/log/?h=Applications/18.08

Since Debian seems a weird mix of old and newer stuff and we should get more consistent versions and updates into it (@ScarlettGatelyClark , @shadeslayer ), it would be great if we make sure that relevant info under "about" is relatively recent and accurate.
In case of marble, there seems 17.08 as package name in testing, but then it shows these infos:
![screenshot_20181215_185832](https://user-images.githubusercontent.com/840070/50045971-41c77680-009c-11e9-8ee1-e219c6e052cc.png)

Whoever from BlueSystems is closest to where or how this might happen with KDE Apps (maybe @aleixpol ?) would be nice to look into this or raise a phab ticket or whatever best to make this work better in the future.

**Comment by star-buck** [comment]
this is important/relevant e.g. here:
https://github.com/blue-systems/netrunner-releases/issues/119

**Comment by star-buck** [comment]
Gwenview About looks better as in terms of kde apps version number,which corresponds to package version info:
![screenshot_20181215_191333](https://user-images.githubusercontent.com/840070/50046087-bb139900-009d-11e9-8d88-99b748daa9ca.png)
still (C) copyright timestamp is weird, could give impression that this has not been worked on since quite long time.
Maybe an automated "end" year could be generated according to when it last time shipped?
so gwenview would extend 2000-2018 for 18.04 version, similar to a website footer where mostly only the starting time is fixed and to avoid an old impression the second year is set to $current year.

So marble should at least show version number 17.08 (which makes it immediate obvious that there are mixed packages from kde application bundle in debian testing ranging from 17.08 to 18.04) and copyright 2007-2017, so it is conistent and in sync with package version stamp:
![screenshot_20181215_192028](https://user-images.githubusercontent.com/840070/50046135-7f2d0380-009e-11e9-93e9-5a831f799efc.png)

**Comment by star-buck** [comment]
To give a positive example, in Discover this is done perfect:
![screenshot_20181215_224939](https://user-images.githubusercontent.com/840070/50047751-fde46980-00bb-11e9-8cb4-af9a644ccf9b.png)

**Comment by star-buck** [comment]
okay, after some updates no longer perfect (the year should be 2019):
![Screenshot_20190422_182117](https://user-images.githubusercontent.com/840070/56510973-b0757e80-652b-11e9-833b-7020143ac285.png)

**Comment by aleixpol** [comment]
https://commits.kde.org/discover/0fca27949ed092fa374fe74b8452a62f7dc2a597

This is a hard-coded string, maybe it would make sense to automate somehow in the plasma release scripts, @jriddell?

**Comment by jriddell** [comment]
Me and Nate have been trying to convince the KDE Applications release managers and key influencers to switch to a unified version number, but they are largely against it.  This is insane and means random numbers all over the place.  It becomes more important as we move to KDE packaging software directly rather than through distros.  Distros of course have always just used the global version number from KDE Applications but it seems to be a point of conflict that KDE folks need to get their head around.

Updating Copyright years isn't really something that should be done automated at release time.  It should be done when it factually correct which is the first time there's changes to a codebase in a new year.  If you want to cheat then just make it a substitution for the output of  QDate::currentDate()

**Comment by star-buck** [comment]
Discover did have updates though in 2019.

**Comment by Pointedstick** [comment]
@aleixpol Can confirm. How odd; the code clearly says 2019:

```
~/kde/src/discover$  (Plasma/5.15) grep -ri "Plasma Development Team" .
./discover/main.cpp:                     KAboutLicense::GPL, i18n("© 2010-2019 Plasma Development Team"));
```

But the UI says 2018.

Tracking this with https://bugs.kde.org/show_bug.cgi?id=406928.
