### ISSUE TITLE
spectacle: when browsing a folder to store the screenshot in, the pregenerated name picture-...png gets removed and name field is empty

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#172]

**Comment by star-buck** [comment]
in neon unstable it seems more that first time it doesnt find the home folder and starts from /root and suggested name is empty...

**Comment by Pointedstick** [comment]
Do you mean during a `Save As...` Operation? If so, cannot reproduce on 18.12.3 or git master. A screen recording would be helpful since custom settings may be at play.

**Comment by star-buck** [comment]
Neon unstable iso, live mode or installed

**Comment by Pointedstick** [comment]
Cannot reproduce in a fresh neon dev unstable VM or with a new user in an existing one, but I may simply not be understanding the problem. Can you confirm that you're seeing this during a `Save As...` operation after taking a screenshot? Alternatively a screen recording would help.

**Comment by star-buck** [comment]
Yes, during save as. Live boot into neon, press Print key, select Save as

**Comment by Pointedstick** [comment]
Confirmed. Tracking this with https://bugs.kde.org/show_bug.cgi?id=406058, and moved it to https://github.com/blue-systems/qa-topics/issues/11
