### ISSUE TITLE
Discover: mouse hover over sorting entries dropdown makes them vanish

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#175]
before:
![screenshot_20190110_164829](https://user-images.githubusercontent.com/840070/50980209-74785980-14f8-11e9-8f29-7a5847da9ebb.png)

after hovering over them with cursor:
![screenshot_20190110_164819](https://user-images.githubusercontent.com/840070/50980220-7d692b00-14f8-11e9-895b-d57c7b8876ce.png)

theme is breeze black, but i assume its for breeze also.

**Comment by Pointedstick** [comment]
This was a legit bug that got fixed a few months ago.
