### ISSUE TITLE
GHNS: Mouse cursors: when installing a new theme, no theme in the grid is visually selected

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#179]
before install:
![Screenshot_20190330_213854](https://user-images.githubusercontent.com/840070/55281437-aef1d580-5334-11e9-8b47-c92247e4720b.png)

installing:
![Screenshot_20190330_213938](https://user-images.githubusercontent.com/840070/55281442-bd3ff180-5334-11e9-9f45-f467f3dc73e5.png)

closing ghns popup again:
![Screenshot_20190330_214000](https://user-images.githubusercontent.com/840070/55281447-c4ff9600-5334-11e9-9e8b-40126cb3a9c4.png)

**Comment by Pointedstick** [comment]
Confirmed, filed upstream as https://bugs.kde.org/show_bug.cgi?id=406084, added to https://github.com/blue-systems/qa-topics/issues/9, and assigned @leinir.

**Comment by leinir** [comment]
https://phabricator.kde.org/D20198
