### ISSUE TITLE
Window Decorations: opening kcm, nothing is visually selected

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#180]
opening dialog, FormaN should be selected, but is not:
![Screenshot_20190330_214459](https://user-images.githubusercontent.com/840070/55281461-2e7fa480-5335-11e9-8ed1-dcc8d95cd2d4.png)

when clicking on FormaN, it gets selected.
Then leaving the dialog it wants to Apply it, even though its already the active one.
![Screenshot_20190330_214520](https://user-images.githubusercontent.com/840070/55281483-58d16200-5335-11e9-8c70-156aa73cd511.png)

this is plasma 5.14.5, maybe its fixed already.

**Comment by Pointedstick** [comment]
Yep, fixed in 5.15.0
