### ISSUE TITLE
calculator widget: make the font bigger

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#198]
![Screenshot_20190528_224739](https://user-images.githubusercontent.com/840070/58511319-d6c9b200-819a-11e9-91e9-50420b799b5a.png)

**Comment by kbroulik** [comment]
I think the easiest would be to change the buttons to `PlasmaComponents 3.0` and then changing the root item to be a `QtQuick Controls 2.0` `Control` and set a `font.pixelSize` based on the applet size which will automagically propagate to all the buttons inside.

**Comment by Pointedstick** [comment]
Thanks for the implementation idea, @kbroulik. I've submitted two patches that implement this enhancement:
- https://phabricator.kde.org/D21502
- https://phabricator.kde.org/D21503

**Comment by Pointedstick** [comment]
Both patches have landed. The button text now resizes in Plasma 5.16, and a visual glitch related to button text escaping from the buttons is fixed in Frameworks 5.60.
