### ISSUE TITLE
In Neon, Plasma addons are listed as separate entries in Discover

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#202]
at least this is the impression one gets how this is presented, which of course contradicts the other presented number of 33MB updates for all
![Screenshot_20191019_212507](https://user-images.githubusercontent.com/840070/67151547-49a50800-f2b7-11e9-9be7-d86fb2f3f067.png)

**Comment by Pointedstick** [comment]
This is https://bugs.kde.org/show_bug.cgi?id=403120, which is tracked in https://github.com/blue-systems/qa-topics/issues/12.

I'm not clear on the workflow here. Since we already have it on https://github.com/blue-systems/qa-topics/issues/12, should we keep this open?

**Comment by Pointedstick** [comment]
Update: this is a Neon packaging bug. See the bug report.

**Comment by hsitter** [comment]
This is fixed as per https://bugs.kde.org/show_bug.cgi?id=413272

![Screenshot_20191025_123722](https://user-images.githubusercontent.com/809987/67564854-3a451500-f724-11e9-9498-f6fb38f83391.png)
