### ISSUE TITLE
Discover: search results do not show category

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#203]
in this screenshot it is also not possble to see what Category the search results are from, so if the category is not repeated in the product title, i have no idea if Arc-Manjaro first entry is a look and feel, Plasma theme or Color scheme:

![Screenshot_20190514_130458](https://user-images.githubusercontent.com/840070/57693243-092ac980-7649-11e9-995d-eff38f18342e.png)

**Comment by Pointedstick** [comment]
Makes sense. I'll work on it.

**Comment by Pointedstick** [comment]
Submitted a patch upstream that does this: https://phabricator.kde.org/D24832

**Comment by Pointedstick** [comment]
Now landed upstream, and it will be a part of Discover 5.18.
