### ISSUE TITLE
Discover: after installing, "install" changes to "remove", but wasnt there also an option to "start/launch"?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#207]
i recall after installation there was a convenient way to start any installed app, that seems missing now

**Comment by aleixpol** [comment]
Yes, there is. It should show for every application that is launchable, even some KNS resources.

Where do you miss it? Any application that can show me the issue?

**Comment by star-buck** [comment]
I installed gltron, but couldnt launch it, just remove.

**Comment by aleixpol** [comment]
Right, same issue as https://github.com/blue-systems/plasma-5.17/issues/206 then :/

**Comment by Pointedstick** [comment]
Yep duplicate of https://github.com/blue-systems/plasma-5.17/issues/206. Let's continue the discussion there.
