### ISSUE TITLE
Discover: clicking once does not show description, clicking on something else and back another time does show description normally

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#215]
![Screenshot_20191103_084243](https://user-images.githubusercontent.com/840070/68082581-83792100-fe16-11e9-89f1-e90d989b600e.png)

second time:
![Screenshot_20191103_084616](https://user-images.githubusercontent.com/840070/68082583-88d66b80-fe16-11e9-851b-955733a072c3.png)

**Comment by star-buck** [comment]
so it looks like the first time, the description wasnt shown in full, but cut... not sure why second time it automatically expanded then though

**Comment by Pointedstick** [comment]
Can reproduce in Neon unstable. Here are the exact steps:

1. Maximize the window
2. Click on "Plasma Addons" in the sidebar
3. Search for "Material"
4. Click on "Materia Manjaro"
5. Click on "Material Manjaro" a second time

The second time you click on it, the description gets longer.

**Comment by aleixpol** [comment]
Fixed in 5.17.
https://commits.kde.org/discover/909dac1e69b74c45bcb0779cbbec30feebdb402c

**Comment by Pointedstick** [comment]
Can confirm fixed now.
