### ISSUE TITLE
dolphin: date info (last modified, accessed, created): change e.g. "last wednesday" simply to "wednesday", to not create ambiguity of meaning this wedsneday or last weeks wednseday

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#217]
idea is to remove "last" from this info here and simply say "wednesday", which is shorter, equally correct, but doesnt have other languages eventually think it could be last weeks wednesday:
![Screenshot_20191206_131233](https://user-images.githubusercontent.com/840070/70322860-8d35e000-182b-11ea-9b89-9b0fb7b0a5ec.png)

googling "last wednsday", first suggestion shown from stackexchange is also this:
![Screenshot_20191206_131804](https://user-images.githubusercontent.com/840070/70322813-68da0380-182b-11ea-9036-e8ba0ff1acfd.png)

**Comment by star-buck** [comment]
@Pointedstick : can you do a suggestion on phab and lets see what people say and brainstorm for a possible solution

**Comment by Pointedstick** [comment]
Will do. I agree that this is confusing.

**Comment by Pointedstick** [comment]
https://phabricator.kde.org/T12349

**Comment by Pointedstick** [comment]
There was widespread agreement, and I submitted a patch to fix it: https://phabricator.kde.org/D25878

**Comment by Pointedstick** [comment]
My patch landed; this should be fixed in Frameworks 5.66.
