### ISSUE TITLE
ghns wallpaper: "use" button doesnt work

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#227]
![Screenshot_20200715_140132](https://user-images.githubusercontent.com/840070/87553955-11462500-c6a3-11ea-897d-8b44fca5d9e7.png)

**Comment by leinir** [comment]
Thanks! Patch up on invent, a nice, trivial (if dumb) sort of thing for once ;)

**Comment by leinir** [comment]
Done :) https://invent.kde.org/frameworks/knewstuff/-/merge_requests/8
