### ISSUE TITLE
"guess the icon size"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#234]
guess what icon size this is:
![Screenshot_20200723_191040](https://user-images.githubusercontent.com/840070/88316561-53f9a400-cd18-11ea-8330-0ff8f1d92f75.png)

**Comment by star-buck** [comment]
yes, its already LARGE (I assumed from those options it be "small medium"):
![Screenshot_20200723_191033](https://user-images.githubusercontent.com/840070/88316630-6e338200-cd18-11ea-87d9-84f1be4f406b.png)

**Comment by star-buck** [comment]
@Manueljlin @notmart so these are obviosuly flawed, suggesting to revisit those sizes and make them sensible.

**Comment by star-buck** [comment]
this is "HUGE":
![Screenshot_20200723_191422](https://user-images.githubusercontent.com/840070/88316890-c36f9380-cd18-11ea-9517-ed8666204ec6.png)


To me this is more "large", huge is missing, as is one step between current huge and large, which imo should become the medium.

So new HUGE=currently missing but even more than current huge
new LARGE=current huge
new medium = current missing size between current huge and current large
maybe eliminate one of the even more tinier steps IMO

**Comment by Manueljlin** [comment]
I guess the size names kind of make sense when you look at the size the icons are available:

Tiny: 16px
Small: 22px
Small Medium: 32px
Medium: 64px downscaled to 48px
Large: 64px
Huge: 64@2x


Maybe we should use this instead:

- Remove the 16px size option on the desktop (keep it for dolphin). This change probably won't break anyone's _workflow_.
- Tiny: 22px
- Small: 32px
- Small medium: True 48px 
- Medium: 64px
- Large: 64@2x/128
- Huge: Depends on how big it's required, 64@4x/256 is way too big imho

**Comment by star-buck** [comment]
We need something between 64 and 128 to be called Medium.

**Comment by star-buck** [comment]
2xtrue 48=96

**Comment by Manueljlin** [comment]
Ok, so something like this
- Remove 16, 22px
- Tiny: 32px
- Small: 48px
- Small medium: 64px
- Medium: 96
- Large: 128
- Huge: 128 upscaled

**Comment by star-buck** [comment]
Or keep one of 16/22px and do:
Tiny: 16 or 22
Small: 32
Small medium: 48
Medium: 64
Medium Large: 96
Large: 128
Huge: 128 upscaled

**Comment by Manueljlin** [comment]
Made a MR: https://invent.kde.org/frameworks/breeze-icons/-/merge_requests/36

**Comment by Pointedstick** [comment]
And here's one that makes use of those nice new icons in Plasma to smooth out the sizes: https://invent.kde.org/plasma/plasma-desktop/-/merge_requests/111

**Comment by Pointedstick** [comment]
The MR just landed upstream. These are now the size steps:

- 22px (smallMedium)
- 32px (medium)
- 48px (large)
- 64px (huge)
- 96px (large * 2)
- 128px (enormous)

This should fix the abrupt jump between the two biggest sizes, and make the two smallest sizes not so similar anymore.
