### ISSUE TITLE
icon size: tiny is really unusable, and all the others should scale up, as large or huge are really not even close to be that

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#246]
this is what i would consider small or small medium, but its large:
![Screenshot_20210921_203134](https://user-images.githubusercontent.com/840070/134227621-45364379-e9b0-4ae2-99e0-35e9d5469b97.png)

and thats huge, which i find quite a jump, still only average, but not truly large or huge:
![Screenshot_20210921_203521](https://user-images.githubusercontent.com/840070/134228089-cecf7cbb-98d0-44e6-97e4-f82633a6db36.png)
:

**Comment by star-buck** [comment]
so the jump between large and huge is too big, i suggest remove tiny, call current small new tiny, current small medium new small, etc., then make current huge a tad smaller and call large and add one at top end that is really bigger than current huge.

**Comment by star-buck** [comment]
i know this is scaled, but the font and all other elements match, and i tested this on normal 1920x1080 and its the same but relatively scaled even further down. so the same suggestion would apply.

**Comment by Pointedstick** [comment]
I have submitted https://invent.kde.org/plasma/plasma-desktop/-/merge_requests/683 to add a new larger size at the top end, and tweaks the menu text to better match the actual sizes.

IMO the smaller sizes are reasonable to use for someone who has a truly enormous number of desktop icons. Not all users carefully curate their desktops; some use it for long-term storage. For these people, having adequately small icon sizes can make sense. My mother and wife are two such people, so I'm somewhat familiar with the use case. :)

**Comment by Pointedstick** [comment]
My merge request was merged, so this should be fixed now!
