### ISSUE TITLE
[gtk settings kcm]: Adwaita icon theme is not listed in dropdown

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#28]
even if fully installed, Adwaita icon theme is not listed as option in dropdown.

**Comment by aleixpol** [comment]
Fixed in Plasma/5.8 branch as of: https://quickgit.kde.org/?p=kde-gtk-config.git&a=commit&h=ac0fd79e06f4c9dd2baaa34f13e8bebec36ba83c

**Comment by star-buck** [comment]
great thanks, should be in 5.8.1 then?

**Comment by aleixpol** [comment]
Yes
