### ISSUE TITLE
[GHNS]: show new Wallpaper Category Names

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#39]
I just stumbled over this and noticed that we still show the filters for the legacy names, even though some of those are no longer in use and have changed name in the clean up:

![screenshot_20161126_093553](https://cloud.githubusercontent.com/assets/840070/20639306/c35e657c-b3bf-11e6-9ed2-6cc6ad3615b9.png)

The ones that are mapped/in use:
Legacy Name -mapped to-> New Name (new ID in parenthesis):

KDE Wallpaper 800x600 -> Wallpaper (58)
KDE Wallpaper 1024x768 -> Abstract (296)
KDE Wallpaper 1280x1024 -> Animals (297)
KDE Wallpaper 1440x900 -> Nature (298)
KDE Wallpaper 1600x1200 -> Beaches and Oceans (307)
KDE Wallpaper (other) -> Wallpapers KDE (299)

All other wallpaper categories should be removed from the filter dropdown, as they seem to pull any kind of non-wallpaper items if selected (Try e.g. 1680x1050).

Long Term, the names of the items should be adjusted and/or mapped to the codenames instead when pulling them instead of matching "KDE Wallpaper 800x600", which is deprecated and no more relevant.

**Comment by notmart** [comment]
I tried to change to new names, but it doesn't work (specifying ids directly in knsrc doesn't either)
in https://api.kde-look.org/ocs/v1/content/categories only the old names are listed.
However the other old categories have been removed now in 5.8 and master, so while the combobox still shows the old category names, at least the broken categories aren't there anymore.

**Comment by star-buck** [comment]
the question is:
Can we ever change the names to the real category names as in the store?
Or do we then break it backwards automatically?
Then what I suggest is we start serving old and new category names over OCS, instead of only the legacy ones and you can start switching from one to the other after a certain version?

**Comment by star-buck** [comment]
it would look like this (you could choose in the future to always show the display_name, and then either still match the name, display_name or even the id to make it less error prone):
```
<category>
<id>58</id>
<name>KDE Wallpaper 800x600</name>
<display_name>KDE Wallpapers</display_name>
</category>
```

**Comment by notmart** [comment]
with https://phabricator.kde.org/D4120 and https://phabricator.kde.org/D4121

the display name are used
![eojxvcu](https://cloud.githubusercontent.com/assets/4526371/21934090/66ccc128-d9a8-11e6-9d66-439330ac2a3c.png)

**Comment by notmart** [comment]
should be testable when new frameworks packages land in neon devel

**Comment by star-buck** [comment]
Now can the dropdown also be ordered by display_name?

**Comment by notmart** [comment]
patch to alphabetically order the list, waiting for review https://phabricator.kde.org/D4156

**Comment by star-buck** [comment]
frameworks 5.31
