### ISSUE TITLE
[dash]: clicking on "all applications", then Widgets, leaves Applications visible instead of showing Widgets

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#43]
![screenshot_20170112_213908](https://cloud.githubusercontent.com/assets/840070/21907390/a66faf14-d90f-11e6-8198-9f0e95c2bb9b.png)

**Comment by eikehein** [comment]
Confirmed, will fix (small logic error).

**Comment by eikehein** [comment]
Fixed in plasma-desktop fb285cdecfa8df5eaf55b9cfdcc1fd10a67ab503.

**Comment by star-buck** [comment]
works correct now
