### ISSUE TITLE
[ghns]: wallpapers: cannot "install" some wallpapers (they seem to download but the button doesnt switch to "uninstall")

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#46]
e.g. https://store.kde.org/p/1161830 :
![screenshot_20170112_221654](https://cloud.githubusercontent.com/assets/840070/21908677/fac227f4-d914-11e6-889d-e3b495d6b3da.png)

**Comment by star-buck** [comment]
seems to affect almost all wallpapers, so this could be on ocsserver side or ghns/kns.
I recall though it still worked fine on 5.8.x, but will check that too in a minute.

**Comment by star-buck** [comment]
odd: affects other ghns stuff too, like mouse cursors, but some could be downloaded, while others failed:
![screenshot_20170112_222243](https://cloud.githubusercontent.com/assets/840070/21908818/b7ba9b5c-d915-11e6-831e-bfebffde8733.png)

needs further investigation tomorrow.

**Comment by notmart** [comment]
the cursor (intrusion 2) is actually broken content on the server.
while the problem of wallpapers is an actual one and should be fixed by
https://commits.kde.org/knewstuff/7993c90088779a3140187c5adf5ee1f04b6c8ff4
update of knewstuff framework package should fix the issue

**Comment by star-buck** [comment]
notmart: is this frameworks side or plasma side? Please provide a clear version, when it should be fixed publicly, like this hopefully is not an issue with kf5.30?
https://www.kde.org/announcements/kde-frameworks-5.30.0.php

**Comment by notmart** [comment]
it's a framework issue (KNewStuff framework) and yes, 5.30 should be affected, so fix would be with 5.31

i can ask if is possible to respin a 5.30.1 tarball for KNewStuff

**Comment by star-buck** [comment]
I would absolutely think so, wallpaper Ghns otherwise is almost completely
broken.

Whoever even tested this once thouroughly (for real and not theory) before
giving it a ship it?

**Comment by notmart** [comment]
5.30.1 has been released with the fix
