### ISSUE TITLE
[window deco kcm]: applying a change causes a crash

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#52]
![screenshot_20170203_171425](https://cloud.githubusercontent.com/assets/840070/22600258/08cfd6da-ea3a-11e6-86d1-e0a24039c814.png)

**Comment by davidedmundson** [comment]
Will do.
Fwiw, I know of this one already, I spent a bit of time on it before relrase

**Comment by davidedmundson** [comment]
Ugh. Hit close whilst typing. It affects all qml kcms. We think caused by some Qt change.
Not identified the exact cause yet, it's deep in qml internals.

**Comment by star-buck** [comment]
While any qml kcm might be affected, its so far actually only happening
with window deco kcm  on neon5.9, using qt5.7.1.

**Comment by davidedmundson** [comment]
The Qt bug report: 
https://bugreports.qt.io/browse/QTBUG-57714

**Comment by davidedmundson** [comment]
FYI, this should be fixed (worked around) in Plasma 5.9.3

See cb481b492271860586c69298395e2ba118239406 and 51c4d6c8db8298dbd471fa91de6cb97bf8b4287a in kscreenlocker

**Comment by star-buck** [comment]
seems fixed, tested with Plasma 5.9.4
