### ISSUE TITLE
clipboard: copy something from firefox, then closing firefox and pasting in e.g. kwrite doesnt work

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#53]
tested on latest neon 5.9 user edition

**Comment by star-buck** [comment]
open firefox
select some text and copy it to clipboard
close firefox
open kwrite
paste shows no output

**Comment by notmart** [comment]
@davidedmundson you mentioned you had some work in progress hack?

**Comment by davidedmundson** [comment]
It's a bug in firefox.

When an app closes it sends a signal to the clipboard manager to say "take ownership of the last thing I copied". 
Klipper listens to this and when it gets that request, it tells X "I now have the latest clipboard contents".

For whatever reason that isn't happening.

We could make klipper repopulate the

**Comment by davidedmundson** [comment]
My above comments were slightly wrong, that clipboard manager spec was obsoleted by the new clipboard management in XFixes.

There was a bug in Qt there.

This fixes it:
http://code.qt.io/cgit/qt/qtbase.git/commit/?id=291eba6f8099a0fec8fbd9cf8a1fb67e5c9f4f8d

Which is in Qt 5.8, not 5.7.

Easiest thing from my POV would be for us to patch Qt with that commit.
However, now I know exactly what's up if we needed to I can patch klipper to work round this.

**Comment by star-buck** [comment]
@davidedmundson : 
so in Qt5.8.x its fixed? will label this green then here?

**Comment by davidedmundson** [comment]
Yep, fixed in Qt5.8.

I did look at trying to fix it into klipper earlier but it wasn't very feasible, it would have involved forking half of Qt's clipboard handling.

**Comment by star-buck** [comment]
confirmed to seem working now.
