### ISSUE TITLE
[kamoso 3.2]: picture and video file naming scheme is wrong

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#6]
month 42:
![kamoso screenshot_20160727_175205](https://cloud.githubusercontent.com/assets/840070/17182191/fa39eb7c-5422-11e6-821f-77c1e3bca978.png)

**Comment by aleixpol** [comment]
Fixed as of http://commits.kde.org/kamoso/2de039758cdc44cbd0342369af893d88df964d78

**Comment by star-buck** [comment]
@aleixpol : what version of kamoso would that to be fixed?

**Comment by aleixpol** [comment]
Kamoso 3.3, which hasn't been released yet. I'll add a todo item.

**Comment by star-buck** [comment]
@aleixpol :  kamoso 3.3 now released?

**Comment by aleixpol** [comment]
3.2.1 released today has this fix: http://download.kde.org/stable/kamoso/3.2/src/

Sorry for being so slow on this one.
