### ISSUE TITLE
TM: IOTM launchers do not stay in place

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#60]
* icon-only TM: 
* sorting of pinned launchers do not stay in place
* start and pin kcalc, close it
* start and pin kate, close it
* drag kate to first spot
* starting kate moves icon to last spot and stays there after closing

**Comment by eikehein** [comment]
Ivan's per-activity launcher pinning work for 5.9 hosed this completely, we've been getting various reports. I need to investigate it soon.

**Comment by eikehein** [comment]
https://bugs.kde.org/show_bug.cgi?id=375924 upstream

**Comment by eikehein** [comment]
I have a solid idea of what's broken now, will probably get fixed tomorrow :)

**Comment by eikehein** [comment]
Fixed by https://commits.kde.org/plasma-workspace/dda4d42e891a386c747fbe0e5698ca019921d3a1

Fix will be in plasma-workspace 5.9.2.

**Comment by eikehein** [comment]
Unfortunately it turned out there's another, second bug in the activities work causing something similar.

Follow-up patch under review: https://phabricator.kde.org/D4749

This second fix should be in 5.9.3.

**Comment by eikehein** [comment]
Second fix landed, will be in plasma-workspace 5.9.3.

So with this, this is hopefully done.

**Comment by star-buck** [comment]
please mark "ready for QA", so one can easily spot whats supposed to be fixed.

**Comment by star-buck** [comment]
@eikehein : please mark this and all other threads of yours that are actually solved with the Green label "ready for QA", thanks.

**Comment by eikehein** [comment]
Added label
