### ISSUE TITLE
kamoso: error while starting

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#62]
netrunner@netrunner-pc:$ kamoso
Playing device changed "/dev/video0"
Cannot initialize model with data QJsonObject() . missing: QJsonValue(string, "urls")
new gamma 103
new gamma 104
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Slider.qml:204:5: QML RangeModel: Binding loop detected for property "value"
New saturation  100
New contrast  100
terminate called after throwing an instance of 'QGlib::Error'
  what():  no property "video-direction" in element "videoflip0"
Aborted

**Comment by aleixpol** [comment]
Can you give me an iso of where this has been tested? it's possibly missing some package installed.

**Comment by star-buck** [comment]
Sure, tested on this one: http://dev.netrunner.com/dev/maui-3-dvd-64bit-build6.iso

**Comment by aleixpol** [comment]
Here's a patch: https://commits.kde.org/kamoso/68c0ec95b4f3f0c51ffab558298758eeeae8c489

Will start the the stable release procedure.

**Comment by aleixpol** [comment]
http://download.kde.org/stable/kamoso/3.2/src/kamoso-3.2.3.tar.xz.mirrorlist

**Comment by aleixpol** [comment]
Leszek found an issue when started without cameras, will issue a new one as soon it's confirmed to work for him.

**Comment by llelectronics** [comment]
Yeah the patch from here: https://cgit.kde.org/kamoso.git/commit/?h=3.2&id=5363bd425a41a12c663e73e2a873df8dc6284684

works and banana man turns up when no camera is found

**Comment by jriddell** [comment]
I built 3.2.3 in Neon user edition and it works fine (although annoyingly not in a docker or virtual machine).

The master build in Neon developer unstable doesn't start and gives this output:

>kamoso 
Playing device changed "/dev/video0"
Cannot initialize model with data QJsonObject() . missing: QJsonValue(string, "urls")
new gamma 111
new gamma 112
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Slider.qml:204:5: QML RangeModel: Binding loop detected for property "value"
New saturation  100
New contrast  100
terminate called after throwing an instance of 'QGlib::Error'
  what():  no property "video-direction" in element "videoflip0"
Aborted

**Comment by star-buck** [comment]
@aleixpol : is the last issue found by Jonathan solved?

**Comment by aleixpol** [comment]
Yes, it was fixed and even confirmed by a user.
https://bugs.kde.org/show_bug.cgi?id=376829
