### ISSUE TITLE
Start Plasma 5.9.3 with nouveau.noaccel=1 (no 3D acceleration)

### ISSUE THREAD

**Issue by UralZima** [blue-systems/plasma-5.9#63]
I am tired of nouveau freeze and lockups. But don't want to switch to shitty nvidia binary driver. So I decided to disable any 3D acceleration, I don't need it. I have already configured XRender as my compositor, but when I boot with nouveau.noaccel=1, after login on sddm, plasma don't start. Segmentation fault on /usr/lib64/libexec/kf5/kscreen_backend_launcher.

Please help me totally disabling any acceleration in KDE PLasma 5.9.3

**Comment by UralZima** [comment]
Please help, plasma must work without any gpu acceleration. Thanks

**Comment by davidedmundson** [comment]
This is not the KDE bug tracker. 
You want https://bugs.kde.org/enter_bug.cgi?product=plasmashell
