### ISSUE TITLE
Mpris2 mediaplayercontrols interfere with last position of played media, e.g. vlc or smplayer

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#69]
this happens tested on netrunner, which has selected "play from start" option for vlc or smplayer, but both seem to ignore the setting and resume newly opened files from the last jump cut done.

Here is someone who found out it was related to mpris2:
https://bbs.archlinux.org/viewtopic.php?pid=1620185#p1620185

Some notes:
It is not solely audacious at fault here, the fault lies in anything that activates mpris2/the mediacontroller.

The mediacontroller also seems to be buggy, as it synchs the time from the active smplayer, but has trouble when one jumps forward or rewind from the controls.

**Comment by star-buck** [comment]
i could do a video later, but anyone could try the latest netrunner ISO
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/amd64/netrunner-desktop/netrunner-20170317.1657-amd64.hybrid.iso

Start a video with smplayer, then click anywhere on the timeline to jump to a certain spot (try 1:00 minute, so other videos dont hump right to the end when doing the next step).

This jumpcut seems to interfere with some mpris2 fucntionality and somehow "store" this marker independent of smplayer or vlc.

After closing smplayer, and opening a different videofile from dolphin, the new file (even if never played before) starts at the exact same spot that the last video was jumped to before.

Deleting all smplayer config files doesnt help, but since the above comment pointed to mediacontroller, I simply removed the volume plasmoid that i knew had also mpris2/mediacontroller functionality.

Once you remove that, there is nothing left as mediacontroller is hidden due to bad functionality anyway, so smplayer no longer starts files from that jumppoint, but always from 0.

I think its likely the cuplrit then, and its bad as it also ssem to affect vlc player in the same way.

**Comment by star-buck** [comment]
https://www.dropbox.com/s/hwhxx1wipqz5yj0/smplayer-mpris2-vokoscreen-2017-03-18_20-12-06.mkv?dl=0
okay, seems i could have done the video faster than explaining that stuff :/

**Comment by davidedmundson** [comment]
You were spot on with your analysis and with which applet you removed in the video. The volume applet.

That volume control from https://github.com/Zren/plasma-applets has a media controller built in. Even though it's not enabled it still loads the media tracking code in the background. It has a somewhat complicated bug which makes it call SetPosition whenever a track changed.

I've made a patch: https://github.com/Zren/plasma-applets/pull/69

Obviously because it's not inside KDE I can't just push it. Hopefully the author will be responsive, otherwise you'll need someone to patch in Netrunner.

**Comment by star-buck** [comment]
Thanks for the applet fix, but isnt it still a more generic bug if a user
simply has mediacontroller enabled besides that volume applet?

E.g. doesnt that erronous behaviour still happen in kde neon, where
mediacontroller isnt hidden default like in netrunner?

**Comment by davidedmundson** [comment]
The upstream KDE plasma media applet doesn't have this bug, it's only Zren's version that does. He copied some code and accidentally broke something when simplifying it.

**Comment by star-buck** [comment]
That would be great, but are you sure about that?
I recall re-enabling mediacontrol in netrunner after removing the
volumeapplet and getting the same behaviour (50% certainty recalling this
right).

**Comment by star-buck** [comment]
closing this for now.
