### ISSUE TITLE
TM: EITM does cut off text too soon in some open tasks, see screenshots

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#74]
Example tasks (its not related to specific apps, more randomly occuring or not):
![tm_20170324_183625](https://cloud.githubusercontent.com/assets/840070/24324220/950a915c-1182-11e7-953a-7fef001b1e98.png)
Settings:
![taskmanager-tasks-cut-too-early_20170324_170655](https://cloud.githubusercontent.com/assets/840070/24324217/859ee150-1182-11e7-9beb-6b3c53309db7.png)

ISO tested on:
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/amd64/netrunner-desktop/netrunner-20170324.1345-amd64.hybrid.iso

**Comment by eikehein** [comment]
This is a known bug in the eliding in QML's Label component, we'll have to fix it upstream in Qt.

**Comment by star-buck** [comment]
Does it happen in non-eitm as well?
I never noticed this as of now really.

**Comment by eikehein** [comment]
Yep, it can happen on anything - basically in some cases you get unlucky and Label elides super early. I remember Kai hitting it and looking into it too, I'll ask him if he made any effort fixing it in Qt. It's just particularly noticable on TM when it happens (because there you want maximum text ...).

**Comment by star-buck** [comment]
Did Qt change something or since when does this noticably happen? Any
official bug report link? Again, never noticed this happen before, not even
recall this on Netrunner 17.01 two months ago.
Since this is severly noticable on current 17.03 ISO i would need a fix,
patch, workaround to solve this before the release.

**Comment by eikehein** [comment]
No, it's always happened in Qt 5 and I haven't noticed it getting particularly worse lately.

**Comment by eikehein** [comment]
Same issue in Folder View:

2017-03-02.log:[16:51:09] <kbroulik> qml eliding y u so stupid :(
2017-03-02.log:[16:51:31] <kbroulik> just thought folderview label sizing in popup was broken, the label has the right size but qt is like, nah, let's just elide waaay too soon randomly

**Comment by eikehein** [comment]
For FV we went with a workaround: https://phabricator.kde.org/D4899

However the TM QML already contains equivalent code to the result in FV, especially if Netrunner already uses the hidden config option to force a maximumLineCount of 1, so the same workaround is apparently not working there (or maybe it doesn't really work in FV either and Kai got lucky).

**Comment by star-buck** [comment]
Has this been reported as bug in bugs.kde.org?
Any link?

**Comment by eikehein** [comment]
Nope, it's never been reported by any user so far. Don't have any links sorry.

**Comment by star-buck** [comment]
On Mar 27, 2017 10:00, "Eike Hein" <notifications@github.com> wrote:
>
> TM QML already contains equivalent code to the result in FV, especially
if Netrunner already uses the hidden config option to force a
maximumLineCount of 1

It would be good if you download the Netrunner ISO and help check things
directly to see how it is actually configured or if there is something
wrong.

**Comment by eikehein** [comment]
Yep, started ISO download immediately earlier already, but the wifi is a bit slow currently so it's about two hours away.

**Comment by eikehein** [comment]
Talked to Kai btw, he didn't look at the upstream code and didn't look up a Qt bug tracker ticket for it either. I looked at the Qt tracker and haven't found anything nor any recent fix commits in qtdeclarative.

**Comment by eikehein** [comment]
Good news.

I looked at the ISO and played around with it after reproducing the problem, and it turns out that the Netrunner-specific config of one text line triggers the bug more easily, but I also found a workaround that addresses that specific situation by setting the wrap mode to NoWrap when maximumLineCount is 1.

Patch for plasma-desktop 5.9: https://commits.kde.org/plasma-desktop/f5f685ecdc630fdcd767e2a6f611b8f43e7f8c3e

And the same patch for Folder View: https://commits.kde.org/plasma-desktop/a03d08a99e86c13ee50407f5189d70bf0a2b37fc

This will be in the next 5.9.x, or Netrunner can backport them now.

**Comment by star-buck** [comment]
fixed in netrunner

**Comment by star-buck** [comment]
@eikehein : Plasma 5.9.4 didnt carry it? (in netrunner rolling it still seems to cut text short...)

**Comment by eikehein** [comment]
@star-buck 5.9.4 is too old, the patch is newer

**Comment by star-buck** [comment]
So 5.9.5 or when?

**Comment by eikehein** [comment]
Yep, according to https://community.kde.org/Schedules/Plasma_5 there's a 5.9.5 release scheduled for April 25th that it will be included in.

**Comment by star-buck** [comment]
kde neon 5.10 beta: works!
