### ISSUE TITLE
simplemenu: meta-key opens menu, but does not close it when pressed again

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#75]
for testing this iso can be used:
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/amd64/netrunner-desktop/netrunner-20170324.1345-amd64.hybrid.iso

**Comment by star-buck** [comment]
note: maybe it is possibly not the latest released version packaged as simplemenu doesnt come with plasma default

**Comment by eikehein** [comment]
This was fixed for the Simple Menu 1.0.1 version which is on the store.

**Comment by star-buck** [comment]
works!
