### ISSUE TITLE
[ksysguard]: scrolling down and selecting a process makes the list to jump back to the top and select an entry there relative to where the mouse cursor was positioned

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#76]
it needs to be the first click, as demonstrated here when first changing sort order it works fine, but second time trying to select an entry right away jumps back to the top:
https://www.dropbox.com/s/ou8oy7acehq5bzp/ksysguard-jump-to-top-2017-03-30_18-02-03.mkv?dl=0

**Comment by notmart** [comment]
that behavior was the sideeffect of an old patch about keyboard navigation https://git.reviewboard.kde.org/r/112258/ where doing this reset to the top *may* make sense when triggered by keyboard navigation (tab), when clicking on the list with the mouse, resetting the view to 0 is always the wrong behavior.
I've removed the list reset logic, and the bug doesn't seem to happen anymore.
I've pushed it to 5.8, 5.9 and master, so each new major and minor release should have the fix

**Comment by notmart** [comment]
will be released in:
5.9.5: 25th april
and 5.10.0 30 may
https://community.kde.org/Schedules/Plasma_5

**Comment by star-buck** [comment]
kde neon 5.10 beta: works.
