### ISSUE TITLE
[colors kcm]: cant edit "Default" scheme, cant edit other themes without saving them afterwards, instead of it becoming the default/temporary used scheme if not saved

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#77]

**Comment by notmart** [comment]
https://phabricator.kde.org/D5399 adresses some of the issues, ie allows to save and overwrite system wide themes.
as a separate one, will try to do a minor redesign of the meaning of the "default" entry (that would become "current" i guess) that would adress the remaining issues

**Comment by star-buck** [comment]
"Current" is better, or maybe even "Cached"

**Comment by notmart** [comment]
https://phabricator.kde.org/D5411 restores the concept of "current" entry, i think it can supersede D5399

**Comment by notmart** [comment]
pushed, will be released together Plasma 5.10 on 30th of may

**Comment by star-buck** [comment]
kde neon 5.10:
pressing "Edit" button while on "Current" theme does nothing

**Comment by notmart** [comment]
fixed it in 5.10 branch and master, should be ok for 5.10 release
