### ISSUE TITLE
[window decoration kcm]: no theme marked/selected

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#78]
![screenshot_20170411_161300](https://cloud.githubusercontent.com/assets/840070/24914017/3b2d5814-1ed3-11e7-93b6-cf41a50ce519.png)

**Comment by davidedmundson** [comment]
Fixed.
Will update when merged.

**Comment by star-buck** [comment]
Thanks.
Can you also check why the sorting is different, e.g. Breeze no longer is
listed before Oygen.

**Comment by davidedmundson** [comment]
Done

**Comment by star-buck** [comment]
which release?

**Comment by davidedmundson** [comment]
Plasma 5.9.5

**Comment by star-buck** [comment]
5.10 beta:
first time opening this dialog, the Breeze theme is selected default.
But even without changing anything, upon leaving the kcm the "Apply" dialog popup comes up, so it thinks it is selected something new?? 
Does anyone test this or just assumes "things surely got fixed this time", since this dialog has been broken from the beginning until now...
