### ISSUE TITLE
[simplemenu]: using mousescrollwheel to go from Fav page to first page of apps sometimes skips to last page instead

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#79]
tested with latest RC based on arch with released packages like Plasma 5.9.4:
http://arch.netrunner.com/ISO/netrunner-rolling-2017.04-RC1-x86_64.iso

**Comment by eikehein** [comment]
Do you know if this using Simple Menu 1.0.1 from the Store or still an old git-based package? Because as per meeting notes, I much improved the mouse wheel code to be less sensitive fairly recently.

I'll check the ISO later.

**Comment by star-buck** [comment]
Will check what arch/aur ships on this iso.

**Comment by eikehein** [comment]
I checked out the ISO and it seems to have the 1.0 code - not the latest, but it does have my updated mouse wheel code (the same as used in Task Manager). So I guess it might need further improvement ... the problem now is that I don't actually have a mouse wheel and just a trackpad, but will see what I can do.

**Comment by eikehein** [comment]
I can soooort of see some wonkyness sometimes, hunting it now ...

**Comment by star-buck** [comment]
thanks, thats appreciated as simplemenu is our new default in netrunner.

**Comment by star-buck** [comment]
@eikehein : any update on this?

**Comment by eikehein** [comment]
Not yet, sorry. I determined at the sprint that it's probably due to libinput wheel acceleration code, as sometimes I get two mouse events from Qt. But nothing since then.

**Comment by eikehein** [comment]
Hmm I bought a cheap PC mouse today to work on this more, but having trouble reproducing it again. The investigation continues ...

**Comment by eikehein** [comment]
Even on Neon I currently can't reproduce ... it may be that it also depends on the mouse model and the one I bought doesn't trigger it. Not sure currently.
