### ISSUE TITLE
fix bug that is supposed to crash Aurorae (to recommend window deco theming via GHNS again)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#80]
https://www.reddit.com/r/kde/comments/64v8rr/using_a_fresh_install_of_kubuntu_and_kwin_is/dg667ep/

**Comment by davidedmundson** [comment]
The commonly re-occuring one that MG is referring to is already fixed.

Fix is in Qt 5.7.1 or higher by a Qt dev (http://code.qt.io/cgit/qt/qtdeclarative.git/commit/?id=4d375f3f2b95bfcb322402df3525db6cc7a723ce)

Neon has that. 
Kubuntu 16.10 (which I guess is what the Reddit poster is using) does not.

**Comment by star-buck** [comment]
Great to hear!

Btw. Is Aurorae supposed to/already work with Wayland?

**Comment by davidedmundson** [comment]
Yes they work on Wayland.

**Comment by star-buck** [comment]
okay, closing this then.
will probably shot then some videos where aurorae appears still lagging/weird when opening/closing windows next.
