### ISSUE TITLE
[window deco kcm]: remove visible lines / artifact

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#83]
https://www.dropbox.com/s/n0eiwf4oa9o1ara/window%20deco%20kcm%20-%20visual%20artifacts%20when%20resizing.mkv?dl=0

**Comment by star-buck** [comment]
still an issue, looks unprofessional

**Comment by star-buck** [comment]
2018 and still an issue:
https://www.dropbox.com/s/8lghoupownigk9m/window-deco-kcm.mkv?dl=0

**Comment by davidedmundson** [comment]
I've finally found it! I'd looked last time it was reported, but with a clear mindset and the right debug tool it was obvious.

It's nothing to do with the KCM or any kind of QtQuick rendering, but just a really stupid bug in plastik. 
Up for review now, will be merged soon \o/
