### ISSUE TITLE
selected wallpaper no longer stays "selected" after "apply button"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#86]
not sure if this go fixed with the other issues related to the wallpaper dialog, so i list this here for completeness:
https://www.dropbox.com/s/ldthhrwg29wbi41/wallpaper-apply.mkv?dl=0

(maybe its a good reason to remove the Apply logic for wallpapers in this case, so any clicked wallpaper simply stays selected like XFCE:
https://www.youtube.com/watch?v=hGY-80Zf5eg&feature=youtu.be&t=625
)

**Comment by eikehein** [comment]
Patch under review: https://phabricator.kde.org/D5440

**Comment by notmart** [comment]
has been pushed, so will ship in Plasma 5.10 on 30th of may https://community.kde.org/Schedules/Plasma_5

**Comment by eikehein** [comment]
I pushed to the 5.9 branch, so it will actually be in 5.9.5 on Apr 25th

**Comment by star-buck** [comment]
neon 5.10 beta works
