### ISSUE TITLE
[folderview]: hover marker flips to first icon after d'n'd any other icon

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#87]
first try:
https://www.dropbox.com/s/ieyk0jhkswmlbro/folderview-hovered-switch.mkv?dl=0

dragged other icons too to make sure its not due to the symlink:
https://www.dropbox.com/s/l31z5so8rz7yhn3/folderview-hover-selected-switch.mkv?dl=0

**Comment by eikehein** [comment]
This is fixed in 5.10 but really difficult to backport due to the heavy surrounding code changes (there is a loooot of polish and performance work in FV 5.10, it was a major focus, me and Kai went to town on it).

**Comment by eikehein** [comment]
This came back due to a Qt thing. We're tracking it here:

https://github.com/blue-systems/plasma-5.11/issues/111

This can be closed.

**Comment by star-buck** [comment]
@eikehein : is it fixed or just tracked there?

**Comment by star-buck** [comment]
i see, closing here
