### ISSUE TITLE
grouping plasmoid: cant click anything inside, e.g. folderview icons

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#88]

**Comment by davidedmundson** [comment]
It seems to be a folderview specific issue,  if I drag a calculator in there it works.

Will investigate and fix.

**Comment by star-buck** [comment]
thanks for the info.

**Comment by davidedmundson** [comment]
Fixed in frameworks 5.34

Turns out it was an underlying frameworks bug that potentially means we have fixes / can remove workarounds elsewhere.

**Comment by star-buck** [comment]
works
