### ISSUE TITLE
[grouping plasmoid]: allow edit the containing plasmoid when right-click on tab-title

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#89]
currently only shows this when right-clicking, no matter what is loaded inside the tab:
![grouping-plasmoid](https://cloud.githubusercontent.com/assets/840070/25042743/9bf0faf4-211a-11e7-8ec7-3c38ca0b1990.png)

**Comment by davidedmundson** [comment]
Added for Plasma 5.10

**Comment by star-buck** [comment]
works
