### ISSUE TITLE
[GHNS]: Zips do not unpack normally, therefore fail to install

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#91]
Latest example:
https://store.kde.org/p/1002412/

This iconset can be found by searching for "Plataro" in GHNS iconset kcm.
It links to github master.zip release file, which gets downloaded correctly and stored in "/tmp", but then fails to unzip and install.
Using ark, one can open and extract the zip just fine though.
A fix would be really welcome to not dissapoint users and creators.

**Comment by notmart** [comment]
fixed in knewstuff (commit 925ec8a17f), that will be released with frameworks 5.34, on May 6th

**Comment by star-buck** [comment]
kde neon 5.10 beta: works!
