### ISSUE TITLE
Menu Alternatives: side-text is squashed

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#92]
1920x1080 resolution and having a hard time to decide if the first shot is Simple or Dash if I cant read barely any text:
![screenshot_20170501_110516](https://cloud.githubusercontent.com/assets/840070/25578427/eb53de02-2e6e-11e7-8e9a-2a82de07d386.png)

**Comment by star-buck** [comment]
I am having a hard time to think maybe what's shipped isnt supposed to look like this, so maybe something went broken on the Netrunner ISO...

**Comment by notmart** [comment]
what plasma release is in the iso? that is a known old problem that is fixed in Plasma 5.9.5 that has been released on 25th of April

**Comment by star-buck** [comment]
Okay, great to know its already solved (screenshot is still 5.9.4).
Still did anyone design the text to be like this on the side or what was
the idea there?

**Comment by notmart** [comment]
yes, icons (at a smaller reasonable size) with text besides was the original design as that was how the widget explorer looked like back then. when the widget explorer look was changed, it was decided to keep this more "menu like", so coherent with kickoff/systray etc.
personally i think big icon with text underneath could visually work, but only with a single column, as opposed to two in the widget explorer.

**Comment by star-buck** [comment]
Marco: Can you add a screenshot how it look in 5.9.5?

**Comment by notmart** [comment]
![spectacle y19611](https://cloud.githubusercontent.com/assets/4526371/25610527/def10968-2f23-11e7-9f1f-30499fcfac27.png)
