### ISSUE TITLE
[discover]: using "libinput", mousewheel scrolling is *very* slow

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#94]
tested in kde neon 5.10 beta

**Comment by aleixpol** [comment]
Discover scrolling is done by Kirigami, @notmart might know how to fix it.

**Comment by star-buck** [comment]
Makes sense.
Since everything else in kde neon 5.10 what was previously slow has been improved, I hope there is some way to fix this also in kirigmai + libinput.

**Comment by notmart** [comment]
this is how discover works here on latest neon unstable running on a laptop and a mouse with a traditional mouse wheel
https://www.youtube.com/watch?v=1s9hqM9equo

is itconsistent with your experience or is it slower for you?

**Comment by star-buck** [comment]
yes, it's like in that video.

**Comment by notmart** [comment]
ok, it's reproducible then, i'll make it faster, probably depending from contents height

**Comment by notmart** [comment]
I tweaked it in kirigami master, launched a rebuild in neon as well. @aleixpol can you give it a bit more testing as well? if current version is good enough, we can then do a new kirigmai release

**Comment by notmart** [comment]
this can be checked again with all master, (also making sure neon has the scrollwheel patch in, which is merged but not sure if is in 5.10.0 already)

**Comment by star-buck** [comment]
@notmart : you mean Qt5.10?

**Comment by notmart** [comment]
i just checked where and when it was pushed.
that Qt patch will be in Qt 5.10.1 and 5.9.5

**Comment by star-buck** [comment]
Is neon bionic supposed to use libinput default?

**Comment by star-buck** [comment]
and to answer: it seems it does.
@notmart : testing on neon dev unstable is useless in this case, as it doesnt use libinput default.

I will continue this in a fresh ticket, and use this as old reference.
