### ISSUE TITLE
Systems Settings: polish Scrollbar look

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#98]
here is what it looks like currently, not sure how to make it visually more pleasing:
![ss-selecteditem-scrollbar-border-overlay](https://user-images.githubusercontent.com/840070/31120329-522001a8-a834-11e7-84a2-e495f00cbff9.jpg)

**Comment by notmart** [comment]
an old version of that kirigami component had the blue zone which ended just before the scrollbar, but i was then told by the vdg that gave too much importance to the scrollbar and looked kinda "broken" especially when the highlighted entry is in a zone outside of the handle, as there would be a blue rectangle finishing, then white gap, then separator line.
but indeed it may look weird when the handle does overlap it..
One idea may be on desktop to still draw the highlighted area overlapping the handle, but dimming it in the part they overlap, so it would both still look like a continuous object and the scrollbar would look a bit less disturbed by it

**Comment by notmart** [comment]
this is pretty much the idea, tough it may look like there is some kind of weird band aid on the right of the column, especially in the default appearance of breeze that has a more minimal scrollbar.
@ohyran : any opinion/ideas on this?
![spectacle tj2322](https://user-images.githubusercontent.com/4526371/31186374-be9ef992-a92e-11e7-85b8-05acd134b372.png)
![spectacle ad2322](https://user-images.githubusercontent.com/4526371/31186405-d2f9e352-a92e-11e7-9449-7115b0d0819c.png)

**Comment by star-buck** [comment]
@notmart : any update for plasma 5.12?
Does the scrollbar disappearing when moving fast over it with the mouse cursor has been fixed?

**Comment by notmart** [comment]
the flicker in the scrollbar on mouseover has been fixed in frameworks so will be in the next (frameworks) release.
as for the look of the scrollbar itself, i'll try to come up with an agreement with the vdg and do something in the desktop breeze style itself

**Comment by notmart** [comment]
phabricator patch on breeze to make scrollbar handles slimmer: https://phabricator.kde.org/D9792

**Comment by notmart** [comment]
new look agreed upon upstream is landed in master for 5.13
