### ISSUE TITLE
Panel: Custom Launcher icon rendered "frizzled out" (can confirm with netrunner logo svg, which was always fine before)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#99]
https://www.reddit.com/r/kde/comments/7jduze/issue_with_app_launcher_icon/

**Comment by star-buck** [comment]
lets get this fixed.

**Comment by eikehein** [comment]
This is caused by Kai's porting from the custom Image element to Icon after he added support for non-rectangular icons and custom paths. I'll have to get his input on it.

**Comment by kbroulik** [comment]
I enabled smooth scaling on the icon, this should help a bit. I cannot reproduce with any of the circular Breeze icons (high dpi problems..), so I asked the author for the original graphic for proper testing. I bet the lines aren't pixel-aligned.

**Comment by kbroulik** [comment]
Should be fixed by
https://cgit.kde.org/plasma-framework.git/commit/?id=639e8684e3b39b43238e1812c1d7f430f86366e3
and
https://cgit.kde.org/plasma-desktop.git/commit/?id=ae219e8941cbef4e4a9da7073994d4874a788424

**Comment by eikehein** [comment]
Thanks Kai!
